//PrimeFaces.locales['sr'] = {
//	closeText : 'Zatvori',
//	prevText : 'Nazad',
//	nextText : 'Napred',
//	monthNames : [ 'Januar', 'Februar', 'Mart', 'April', 'Maj', 'Jun', 'Jul',
//			'Avgust', 'Septembar', 'Oktobar', 'Novembar', 'Decembar' ],
//	monthNamesShort : [ 'Jan', 'Feb', 'Mar', 'Apr', 'Maj', 'Jun', 'Jul', 'Avg',
//			'Sep', 'Okt', 'Nov', 'Dec' ],
//	dayNames : [ 'Nedelja', 'Ponedeljak', 'Utorak', 'Sreda', 'Četvrtak',
//			'Petak', 'Subota' ],
//	dayNamesShort : [ 'Ned', 'Pon', 'Uto', 'Sre', 'Čet', 'Petak', 'Sub' ],
//	dayNamesMin : [ 'N', 'P', 'U', 'S', 'Č', 'P ', 'S' ],
//	weekHeader : 'Nedelja',
//	firstDay : 1,
//	isRTL : false,
//	showMonthAfterYear : false,
//	yearSuffix : '',
//	timeOnlyTitle : 'Samo Vreme',
//	timeText : 'Vreme',
//	hourText : 'Sat',
//	minuteText : 'Minut',
//	secondText : 'Sekund',
//	currentText : 'Danas',
//	ampm : false,
//	month : 'Mesec',
//	week : 'Nedelja',
//	day : 'Dan',
//	allDayText : 'Ceo dan'
//};

 PrimeFaces.locales['sr'] = {
	closeText : 'Затвори',
	prevText : 'Назад',
	nextText : 'Напред',
	monthNames : [ 'Јануар', 'Фебруар', 'Март', 'Април', 'Мај', 'Јун', 'Јул',
			'Август', 'Септембар', 'Октобар', 'Новембар', 'Децембар' ],
	monthNamesShort : [ 'Јан', 'Феб', 'Мар', 'Апр', 'Мај', 'Јун', 'Јул', 'Авг',
			'Сеп', 'Окт', 'Нов', 'Дец' ],
	dayNames : [ 'Недеља', 'Понедељак', 'Уторак', 'Среда', 'Четвртак', 'Петак',
			'Субота' ],
	dayNamesShort : [ 'Нед', 'Пон', 'Уто', 'Сре', 'Чет', 'Петак', 'Суб' ],
	dayNamesMin : [ 'Н', 'П', 'У', 'С', 'Ч', 'П ', 'С' ],
	weekHeader : 'Недеља',
	firstDay : 1,
	isRTL : false,
	showMonthAfterYear : false,
	yearSuffix : '',
	timeOnlyTitle : 'Само Време',
	timeText : 'Време',
	hourText : 'Сат',
	minuteText : 'Минут',
	secondText : 'Секунд',
	currentText : 'Данас',
	ampm : false,
	month : 'Месец',
	week : 'Недеља',
	day : 'Дан',
	allDayText : 'Цео дан'
};
